"""Redeploy the 17 contracts whose bytecode no longer matches source.

Deployment only. Governance moved to the Safe in 0007, so the deployer can no
longer touch a registry: every one of these has to be pointed at through
startAddressUpdateToRegistry + confirmAddressUpdateToRegistry, under timelock,
by the Safe. This migration deploys and then prints that calldata.

Each contract is recorded in the manifest under a "<Name>V2" label so the
existing entries keep describing what RipeHq, VaultBook, Switchboard and
PriceDesk actually point at. Nothing here changes the live wiring.

Run `python scripts/prepare_defaults.py` first. MissionControl and Ledger copy
their defaults into storage at construction, so building them against
DefaultsRobinhood -- the LAUNCH config -- would make the replacements come up
forgetting every asset governance has registered since. That script writes
DefaultsRobinhoodLive.vy from the live chain; review the diff before running
this.

Constructor arguments are identical to the originals in 0001/0002/0004/0005
and 0008. The 08-05 and 08-06 changes altered internals only -- every
signature below was re-checked against the compiled ABI and none moved.
"""

from scripts.utils import log
from scripts.utils.migration import Migration

from config.robinhood_launch import (
    HR_MAX_TIMELOCK,
    HR_MIN_TIMELOCK,
    LEDGER_ACTION_BLOCK_SOURCE,
    LOOTBOX_DEPOSIT_REWARD,
    LOOTBOX_MIN_SEND_INTERVAL,
    LOOTBOX_SEND_INTERVAL,
    LOOTBOX_YIELD_BONUS,
    PRICE_CHANGE_MAX_TIMELOCK,
    PRICE_CHANGE_MIN_TIMELOCK,
    RIPE_WETH_POOL,
    STALE_WINDOW_MAX,
    STALE_WINDOW_MIN,
    SWITCHBOARD_MAX_TIMELOCK,
    SWITCHBOARD_MIN_TIMELOCK,
    TELLER_SHOULD_PAUSE,
    ZERO_ADDRESS,
)

# Which registry owns each slot. The ids were read off chain.
RIPE_HQ = "RipeHq"
VAULT_BOOK = "VaultBook"
SWITCHBOARD = "Switchboard"
PRICE_DESK = "PriceDesk"


def _update_calldata(reg_id, new_addr):
    """The two calls the Safe makes for one registry slot."""
    from eth_abi.abi import encode
    from web3 import Web3

    start = Web3.keccak(text="startAddressUpdateToRegistry(uint256,address)")[:4]
    start += encode(["uint256", "address"], [reg_id, new_addr])
    confirm = Web3.keccak(text="confirmAddressUpdateToRegistry(uint256)")[:4]
    confirm += encode(["uint256"], [reg_id])
    return start.hex(), confirm.hex()


def migrate(migration: Migration):
    hq = migration.get_contract("RipeHq")
    ripe_token = migration.get_address("RipeToken")

    # Unchanged since launch, so the replacement takes the address already on
    # chain rather than getting a fresh copy.
    bond_booster = migration.get_contract("BondBooster")

    log.h1("Deploying DefaultsRobinhoodLive")

    # Generated by scripts/prepare_defaults.py from the live deployment. Both
    # MissionControl and Ledger read it at construction, so it goes first. No
    # constructor: every address it needs is already live, so the generator
    # writes them in as constants.
    defaults = migration.deploy("DefaultsRobinhoodLive")

    updates = []

    def redeploy(name, registry, reg_id, *args):
        log.h2(f"Deploying {name}")
        contract = migration.deploy(name, *args, label=f"{name}V2")
        updates.append((name, registry, reg_id, contract.address))
        return contract

    log.h1("Redeploying core departments")

    # Ledger reads ripeAvailFor* from defaults. Because prepare_defaults
    # sources those from the LIVE Ledger, the replacement inherits what has
    # already been emitted instead of resetting to the launch allocation. Its
    # other state -- deposit points, vault participation, lastTouch -- does
    # NOT carry over.
    redeploy("Ledger", RIPE_HQ, 4, hq, defaults, LEDGER_ACTION_BLOCK_SOURCE)
    redeploy("MissionControl", RIPE_HQ, 5, hq, defaults)
    redeploy("AuctionHouse", RIPE_HQ, 9, hq)
    redeploy("BondRoom", RIPE_HQ, 12, hq, bond_booster)
    redeploy("CreditEngine", RIPE_HQ, 13, hq)
    redeploy("HumanResources", RIPE_HQ, 15, hq, HR_MIN_TIMELOCK, HR_MAX_TIMELOCK)
    redeploy(
        "Lootbox", RIPE_HQ, 16, hq,
        LOOTBOX_MIN_SEND_INTERVAL,
        LOOTBOX_SEND_INTERVAL,
        LOOTBOX_DEPOSIT_REWARD,
        LOOTBOX_YIELD_BONUS,
    )
    redeploy("Teller", RIPE_HQ, 17, hq, TELLER_SHOULD_PAUSE)
    redeploy("CreditRedeem", RIPE_HQ, 19, hq)

    log.h1("Redeploying vaults")

    redeploy("StabilityPool", VAULT_BOOK, 1, hq)
    redeploy("RipeGov", VAULT_BOOK, 2, hq)
    redeploy("SimpleErc20", VAULT_BOOK, 3, hq)

    log.h1("Redeploying switchboards")

    # Alpha alone takes the stale-window band before its timelocks.
    redeploy(
        "SwitchboardAlpha", SWITCHBOARD, 1, hq, ZERO_ADDRESS,
        STALE_WINDOW_MIN,
        STALE_WINDOW_MAX,
        SWITCHBOARD_MIN_TIMELOCK,
        SWITCHBOARD_MAX_TIMELOCK,
    )
    redeploy(
        "SwitchboardBravo", SWITCHBOARD, 2, hq, ZERO_ADDRESS,
        SWITCHBOARD_MIN_TIMELOCK, SWITCHBOARD_MAX_TIMELOCK,
    )
    redeploy(
        "SwitchboardCharlie", SWITCHBOARD, 3, hq, ZERO_ADDRESS,
        SWITCHBOARD_MIN_TIMELOCK, SWITCHBOARD_MAX_TIMELOCK,
    )
    redeploy(
        "SwitchboardEcho", SWITCHBOARD, 5, hq, ZERO_ADDRESS,
        SWITCHBOARD_MIN_TIMELOCK, SWITCHBOARD_MAX_TIMELOCK,
    )

    log.h1("Redeploying price sources")

    # Matches 0008. The replacement starts with an EMPTY snapshot ring, so
    # getPrice reads zero until one is written -- see the note at the end.
    redeploy(
        "UniswapV2Prices", PRICE_DESK, 3, hq, ZERO_ADDRESS,
        RIPE_WETH_POOL,
        ripe_token,
        PRICE_CHANGE_MIN_TIMELOCK,
        PRICE_CHANGE_MAX_TIMELOCK,
    )

    log.h1("Registry updates for the Safe")

    for registry in (RIPE_HQ, VAULT_BOOK, SWITCHBOARD, PRICE_DESK):
        rows = [u for u in updates if u[1] == registry]
        if not rows:
            continue
        log.h2(f"{registry} @ {migration.get_address(registry)}")
        for name, _, reg_id, addr in rows:
            start, confirm = _update_calldata(reg_id, addr)
            log.info(f"\t{name} -> id {reg_id} -> {addr}")
            log.info(f"\t  [1] 0x{start}")
            log.info(f"\t  [2] 0x{confirm}   (after timelock)")

    log.h2("Still required afterwards")
    log.info("\tSwitchboardAlpha.addPriceSnapshot(RIPE, 3)")
    log.info("\t  The replacement UniswapV2Prices has no snapshots, and")
    log.info("\t  getPrice returns min(weightedPrice, spot) -- an empty ring")
    log.info("\t  means RIPE prices at zero until one is written.")
