"""Static forward plan for 16 registered replacement candidates.

Deployment and Safe-action preparation only. Governance moved to the Safe in
0007, so the deployer cannot touch a registry. Every replacement is recorded
under a unique ``*Candidate0009`` manifest label; the existing canonical label
therefore continues to identify the active generation. This migration emits
the HumanResources pre-activation timelock call plus the exact
``startAddressUpdateToRegistry`` and ``confirmAddressUpdateToRegistry``
calldata. A later migration must read each registry slot and each action
timelock back and only then promote the complete candidate record to the
canonical manifest label. Deploying changes no live wiring on its own.

Ledger is bytecode-stale too and is DELIBERATELY excluded. It is the only
contract here holding accounting nobody can rebuild -- accrued deposit and
borrow points, unclaimed ripeRewards, per-user vault participation -- and a
replacement starts empty. Its remaining delta is an internal refactor with no
new external function (removeVaultFromUserForMigration was withdrawn in #75
and routed through Lootbox instead), and every Ledger call site in the new
contracts was checked to resolve against the deployed selectors. Redeploy it
only when something actually needs it, and before real deposits accumulate.

Run `python scripts/prepare_defaults.py` first. MissionControl copies its
defaults into storage at construction, so building it against
DefaultsRobinhood -- the LAUNCH config -- would make the replacement come up
forgetting every asset governance has registered since. That script writes
DefaultsRobinhoodLive.vy from the live chain; review the diff before running
this.

Constructor shapes remain compatible with the original deployment arguments,
but external ABIs did move. In particular, Teller intentionally removed the
single-item auction, collateral-redemption, Stability Pool claim, and
Stability Pool redemption families; StabilityPool intentionally stopped
exporting ``valueToShares`` and ``sharesToValue``. Safe tooling and every
off-repository consumer must use the regenerated ABIs before activation.

UniswapV2Prices is intentionally absent. Its deployed instance is a direct
monitoring surface and must never occupy a PriceDesk registry slot.

The H-06 Robinhood runner deliberately forbids this legacy deploy/send API.
This module is therefore a reviewable action plan, not an executable
production migration, until converted to typed ``MIGRATION_STAGE`` actions and
the separately authorized executor/manifest lifecycle.
"""

from scripts.utils import log
from scripts.utils.migration import Migration

from config.robinhood_launch import (
    HR_MAX_TIMELOCK,
    HR_MIN_TIMELOCK,
    LOOTBOX_DEPOSIT_REWARD,
    LOOTBOX_MIN_SEND_INTERVAL,
    LOOTBOX_SEND_INTERVAL,
    LOOTBOX_YIELD_BONUS,
    STALE_WINDOW_MAX,
    STALE_WINDOW_MIN,
    SWITCHBOARD_MAX_TIMELOCK,
    SWITCHBOARD_MIN_TIMELOCK,
    TELLER_SHOULD_PAUSE,
    ZERO_ADDRESS,
)

# Which registry owns each slot. The ids were read off chain.
RIPE_HQ = "RipeHq"
VAULT_BOOK = "VaultBook"
SWITCHBOARD = "Switchboard"
CANDIDATE_SUFFIX = "Candidate0009"


def _update_calldata(reg_id, new_addr):
    """The two calls the Safe makes for one registry slot."""
    from eth_abi.abi import encode
    from web3 import Web3

    start = Web3.keccak(text="startAddressUpdateToRegistry(uint256,address)")[:4]
    start += encode(["uint256", "address"], [reg_id, new_addr])
    confirm = Web3.keccak(text="confirmAddressUpdateToRegistry(uint256)")[:4]
    confirm += encode(["uint256"], [reg_id])
    return start.hex(), confirm.hex()


def _setup_action_timelock_calldata(selected):
    """Safe call used to finish a zero-local-governance candidate."""
    from eth_abi.abi import encode
    from web3 import Web3

    call = Web3.keccak(text="setActionTimeLockAfterSetup(uint256)")[:4]
    call += encode(["uint256"], [selected])
    return call.hex()


def migrate(migration: Migration):
    hq = migration.get_contract("RipeHq")

    # Unchanged since launch, so the replacement takes the address already on
    # chain rather than getting a fresh copy.
    bond_booster = migration.get_contract("BondBooster")

    log.h1("Deploying DefaultsRobinhoodLive")

    # Generated by scripts/prepare_defaults.py from the live deployment. Both
    # MissionControl and Ledger read it at construction, so it goes first. No
    # constructor: every address it needs is already live, so the generator
    # writes them in as constants.
    defaults = migration.deploy(
        "DefaultsRobinhoodLive",
        label="DefaultsRobinhoodLiveCandidate0009",
    )

    updates = []

    def candidate_label(name):
        return f"{name}{CANDIDATE_SUFFIX}"

    def redeploy(name, registry, reg_id, *args):
        log.h2(f"Deploying {name}")
        label = candidate_label(name)
        contract = migration.deploy(name, *args, label=label)
        updates.append((name, label, registry, reg_id, contract.address))
        return contract

    def finalize_local_candidate(contract, expected_minimum):
        """Finish setup while the deployer still holds temporary local gov."""
        assert int(contract.actionTimeLock()) == 0
        selected = int(contract.minActionTimeLock())
        assert selected == expected_minimum and selected != 0
        migration.execute(
            contract.setActionTimeLockAfterSetup,
            selected,
        )
        assert int(contract.actionTimeLock()) == selected
        migration.execute(contract.relinquishGov)
        assert contract.governance() == ZERO_ADDRESS

    log.h1("Redeploying core departments")

    redeploy("MissionControl", RIPE_HQ, 5, hq, defaults)
    redeploy("AuctionHouse", RIPE_HQ, 9, hq)
    redeploy("BondRoom", RIPE_HQ, 12, hq, bond_booster)
    redeploy("CreditEngine", RIPE_HQ, 13, hq)
    human_resources = redeploy(
        "HumanResources",
        RIPE_HQ,
        15,
        hq,
        HR_MIN_TIMELOCK,
        HR_MAX_TIMELOCK,
    )
    redeploy(
        "Lootbox", RIPE_HQ, 16, hq,
        LOOTBOX_MIN_SEND_INTERVAL,
        LOOTBOX_SEND_INTERVAL,
        LOOTBOX_DEPOSIT_REWARD,
        LOOTBOX_YIELD_BONUS,
    )
    redeploy("Teller", RIPE_HQ, 17, hq, TELLER_SHOULD_PAUSE)
    redeploy("CreditRedeem", RIPE_HQ, 19, hq)
    redeploy("TellerUtils", RIPE_HQ, 20, hq)

    log.h1("Redeploying vaults")

    redeploy("StabilityPool", VAULT_BOOK, 1, hq)
    redeploy("RipeGov", VAULT_BOOK, 2, hq)
    redeploy("SimpleErc20", VAULT_BOOK, 3, hq)

    log.h1("Redeploying switchboards")

    # Alpha alone takes the stale-window band before its timelocks.
    switchboard_alpha = redeploy(
        "SwitchboardAlpha", SWITCHBOARD, 1, hq, migration.account(),
        STALE_WINDOW_MIN,
        STALE_WINDOW_MAX,
        SWITCHBOARD_MIN_TIMELOCK,
        SWITCHBOARD_MAX_TIMELOCK,
    )
    switchboard_bravo = redeploy(
        "SwitchboardBravo", SWITCHBOARD, 2, hq, migration.account(),
        SWITCHBOARD_MIN_TIMELOCK, SWITCHBOARD_MAX_TIMELOCK,
    )
    switchboard_charlie = redeploy(
        "SwitchboardCharlie", SWITCHBOARD, 3, hq, migration.account(),
        SWITCHBOARD_MIN_TIMELOCK, SWITCHBOARD_MAX_TIMELOCK,
    )
    switchboard_echo = redeploy(
        "SwitchboardEcho", SWITCHBOARD, 5, hq, migration.account(),
        SWITCHBOARD_MIN_TIMELOCK, SWITCHBOARD_MAX_TIMELOCK,
    )

    # These candidates can use temporary local governance and are finalized
    # before any Safe registry call is prepared.
    for component in (
        switchboard_alpha,
        switchboard_bravo,
        switchboard_charlie,
        switchboard_echo,
    ):
        finalize_local_candidate(component, SWITCHBOARD_MIN_TIMELOCK)

    # HumanResources hard-codes empty local governance in its constructor, so
    # only RipeHq governance (the Safe) can finish setup. This call must execute
    # and read back before the registry start below; activating a zero-timelock
    # replacement even briefly is unsupported.
    assert int(human_resources.actionTimeLock()) == 0
    hr_selected = int(human_resources.minActionTimeLock())
    assert hr_selected == HR_MIN_TIMELOCK and hr_selected != 0
    hr_setup = _setup_action_timelock_calldata(hr_selected)
    log.h1("HumanResources pre-activation Safe action")
    log.info(f"\ttarget: {human_resources.address}")
    log.info(f"\t[setup] 0x{hr_setup}")
    log.info("\tRequire actionTimeLock readback before any registry start.")

    log.h1("Registry updates for the Safe")

    for registry in (RIPE_HQ, VAULT_BOOK, SWITCHBOARD):
        rows = [u for u in updates if u[2] == registry]
        if not rows:
            continue
        registry_contract = migration.get_contract(registry)
        log.h2(f"{registry} @ {registry_contract.address}")
        for name, label, _, reg_id, addr in rows:
            active = registry_contract.getAddr(reg_id)
            assert active != addr, f"{name} candidate is already active"
            start, confirm = _update_calldata(reg_id, addr)
            log.info(f"\t{name} [{label}] -> id {reg_id}")
            log.info(f"\t  active:    {active}")
            log.info(f"\t  candidate: {addr}")
            log.info(f"\t  [1] 0x{start}")
            log.info(f"\t  [2] 0x{confirm}   (after timelock)")
