MIGRATION_STAGE = {
    "migration_id": "0100",
    "semantic_id": "tokens-and-ripe-hq",
    "stage_kind": "deployment",
    "actions": (
        {
            "semantic_action_id": "deploy-green-token",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-001",
            "artifact": "GreenToken",
            "constructor": (
                "binding:initial-ripe-hq",
                "binding:temporary-local-governance",
                "input:Deployment.DP-05.timelocks.TokenHq.minTimeLock",
                "input:Deployment.DP-05.timelocks.TokenHq.maxTimeLock",
                "input:Deployment.DP-19.supply.GREEN.amount",
                "input:Deployment.DP-19.supply.GREEN.recipient",
            ),
            "provides": ("address:GREEN_TOKEN",),
            "postconditions": ("green-token-deployed", "green-mint-not-granted"),
        },
        {
            "semantic_action_id": "deploy-ripe-token",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-002",
            "artifact": "RipeToken",
            "constructor": (
                "binding:initial-ripe-hq",
                "binding:temporary-local-governance",
                "input:Deployment.DP-05.timelocks.TokenHq.minTimeLock",
                "input:Deployment.DP-05.timelocks.TokenHq.maxTimeLock",
                "input:Deployment.DP-19.supply.RIPE.amount",
                "input:Deployment.DP-19.supply.RIPE.recipient",
            ),
            "provides": ("address:RIPE_TOKEN",),
            "postconditions": ("ripe-token-deployed", "ripe-mint-not-granted"),
        },
        {
            "semantic_action_id": "deploy-savings-green",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-003",
            "artifact": "SavingsGreen",
            "constructor": (
                "address:GREEN_TOKEN",
                "binding:initial-ripe-hq",
                "binding:temporary-local-governance",
                "input:Deployment.DP-05.timelocks.TokenHq.minTimeLock",
                "input:Deployment.DP-05.timelocks.TokenHq.maxTimeLock",
                "input:Deployment.DP-19.supply.SGREEN.amount",
                "input:Deployment.DP-19.supply.SGREEN.recipient",
            ),
            "provides": ("address:SGREEN_TOKEN",),
            "postconditions": ("savings-green-deployed", "savings-path-not-activated"),
        },
        {
            "semantic_action_id": "deploy-ripe-hq",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-004",
            "artifact": "RipeHq",
            "constructor": (
                "address:GREEN_TOKEN",
                "address:SGREEN_TOKEN",
                "address:RIPE_TOKEN",
                "binding:temporary-local-governance",
                "input:Deployment.DP-05.timelocks.RipeHq.minTimeLock",
                "input:Deployment.DP-05.timelocks.RipeHq.maxTimeLock",
                "input:Deployment.DP-05.timelocks.AddressRegistry.minDelay",
                "input:Deployment.DP-05.timelocks.AddressRegistry.maxDelay",
            ),
            "provides": ("address:RIPE_HQ",),
            "postconditions": ("ripe-hq-deployed", "global-mint-disabled-before-configuration"),
        },
        {
            "semantic_action_id": "assert-ripe-hq-token-row-1",
            "kind": "registration",
            "operation": "assert-constructor-registration",
            "component_id": "CM-001",
            "registry_ref": "registry:ripe_hq:CM-001",
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "assert-ripe-hq-token-row-2",
            "kind": "registration",
            "operation": "assert-constructor-registration",
            "component_id": "CM-003",
            "registry_ref": "registry:ripe_hq:CM-003",
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "assert-ripe-hq-token-row-3",
            "kind": "registration",
            "operation": "assert-constructor-registration",
            "component_id": "CM-002",
            "registry_ref": "registry:ripe_hq:CM-002",
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "deploy-training-wheels",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-006",
            "artifact": "TrainingWheels",
            "constructor": (
                "address:RIPE_HQ",
                "input:Deployment.DP-18.roles.trainingWheelsAllowlist",
            ),
            "provides": ("address:TRAINING_WHEELS",),
            "postconditions": ("training-wheels-deployed",),
        },
        {
            "semantic_action_id": "bind-contributor-template",
            "kind": "configuration",
            "operation": "bind-approved-preexisting-or-produced-address",
            "component_id": "CM-049",
            "requires": ("binding:contributor-template",),
            "provides": ("address:CONTRIBUTOR_TEMPLATE",),
            "postconditions": ("contributor-component-remains-omitted",),
        },
        {
            "semantic_action_id": "deploy-defaults-robinhood",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-049",
            "artifact": "DefaultsRobinhood",
            "constructor": (
                "address:CONTRIBUTOR_TEMPLATE",
                "address:TRAINING_WHEELS",
                "address:RIPE_TOKEN",
                "address:GREEN_TOKEN",
                "address:SGREEN_TOKEN",
                "address:USDG",
                "address:WETH",
                "address:STEAKHOUSE_USDG_VAULT",
            ),
            "provides": ("address:DEFAULTS_ROBINHOOD",),
            "postconditions": ("defaults-robinhood-deployed", "defaults-constructor-provenance-preserved"),
        },
        {
            "semantic_action_id": "finish-token-hq-bindings",
            "kind": "configuration",
            "operation": "finish-token-setup",
            "component_id": "CM-004",
            "requires": ("address:GREEN_TOKEN", "address:RIPE_TOKEN", "address:SGREEN_TOKEN", "address:RIPE_HQ"),
            "postconditions": ("all-three-token-hq-bindings-exact",),
        },
    ),
}


def migrate(migration):
    migration.apply_robinhood_stage(MIGRATION_STAGE)
