MIGRATION_STAGE = {
    "migration_id": "0300",
    "semantic_id": "switchboards",
    "stage_kind": "deployment",
    "actions": (
        {
            "semantic_action_id": "deploy-switchboard",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-010",
            "artifact": "Switchboard",
            "constructor": ("address:RIPE_HQ", "binding:no-local-governance", "input:Deployment.DP-05.timelocks.LocalGov.minTimeLock", "input:Deployment.DP-05.timelocks.LocalGov.maxTimeLock"),
            "provides": ("address:SWITCHBOARD",),
            "postconditions": ("switchboard-deployed",),
        },
        {
            "semantic_action_id": "deploy-switchboard-alpha",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-011",
            "artifact": "SwitchboardAlpha",
            "constructor": ("address:RIPE_HQ", "binding:no-local-governance", "input:Deployment.DP-17.staleWindows.alphaMinimum", "input:Deployment.DP-17.staleWindows.alphaMaximum", "input:Deployment.DP-05.timelocks.SwitchboardAlpha.minTimeLock", "input:Deployment.DP-05.timelocks.SwitchboardAlpha.maxTimeLock"),
            "provides": ("address:SWITCHBOARD_ALPHA",),
            "postconditions": ("switchboard-alpha-deployed",),
        },
        {
            "semantic_action_id": "register-switchboard-alpha",
            "kind": "registration",
            "operation": "register-and-confirm",
            "component_id": "CM-011",
            "registry_ref": "registry:switchboard:CM-011",
            "requires": ("address:SWITCHBOARD_ALPHA",),
            "abort_if": ("returned-registry-id-mismatch",),
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "deploy-switchboard-bravo",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-012",
            "artifact": "SwitchboardBravo",
            "constructor": ("address:RIPE_HQ", "binding:no-local-governance", "input:Deployment.DP-05.timelocks.SwitchboardBravo.minTimeLock", "input:Deployment.DP-05.timelocks.SwitchboardBravo.maxTimeLock"),
            "provides": ("address:SWITCHBOARD_BRAVO",),
            "postconditions": ("switchboard-bravo-deployed", "unsupported-capabilities-withheld"),
        },
        {
            "semantic_action_id": "register-switchboard-bravo",
            "kind": "registration",
            "operation": "register-and-confirm",
            "component_id": "CM-012",
            "registry_ref": "registry:switchboard:CM-012",
            "requires": ("address:SWITCHBOARD_BRAVO",),
            "abort_if": ("returned-registry-id-mismatch",),
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "deploy-switchboard-charlie",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-013",
            "artifact": "SwitchboardCharlie",
            "constructor": ("address:RIPE_HQ", "binding:no-local-governance", "input:Deployment.DP-05.timelocks.SwitchboardCharlie.minTimeLock", "input:Deployment.DP-05.timelocks.SwitchboardCharlie.maxTimeLock"),
            "provides": ("address:SWITCHBOARD_CHARLIE",),
            "postconditions": ("switchboard-charlie-deployed", "reward-promotion-not-implied"),
        },
        {
            "semantic_action_id": "register-switchboard-charlie",
            "kind": "registration",
            "operation": "register-and-confirm",
            "component_id": "CM-013",
            "registry_ref": "registry:switchboard:CM-013",
            "requires": ("address:SWITCHBOARD_CHARLIE",),
            "abort_if": ("returned-registry-id-mismatch",),
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "deploy-switchboard-delta",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-014",
            "artifact": "SwitchboardDelta",
            "constructor": ("address:RIPE_HQ", "binding:no-local-governance", "input:Deployment.DP-05.timelocks.SwitchboardDelta.minTimeLock", "input:Deployment.DP-05.timelocks.SwitchboardDelta.maxTimeLock"),
            "provides": ("address:SWITCHBOARD_DELTA",),
            "postconditions": ("switchboard-delta-deployed", "deleverage-cooldown-zero"),
        },
        {
            "semantic_action_id": "register-switchboard-delta",
            "kind": "registration",
            "operation": "register-and-confirm",
            "component_id": "CM-014",
            "registry_ref": "registry:switchboard:CM-014",
            "requires": ("address:SWITCHBOARD_DELTA",),
            "abort_if": ("returned-registry-id-mismatch",),
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "deploy-switchboard-echo",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-046",
            "artifact": "SwitchboardEcho",
            "constructor": ("address:RIPE_HQ", "binding:no-local-governance", "input:Deployment.DP-05.timelocks.SwitchboardEcho.minTimeLock", "input:Deployment.DP-05.timelocks.SwitchboardEcho.maxTimeLock"),
            "provides": ("address:SWITCHBOARD_ECHO",),
            "postconditions": ("switchboard-echo-deployed", "psm-activation-absent"),
        },
        {
            "semantic_action_id": "register-switchboard-echo",
            "kind": "registration",
            "operation": "register-and-confirm",
            "component_id": "CM-046",
            "registry_ref": "registry:switchboard:CM-046",
            "requires": ("address:SWITCHBOARD_ECHO",),
            "abort_if": ("returned-registry-id-mismatch",),
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "register-switchboard-in-ripe-hq",
            "kind": "registration",
            "operation": "register-and-confirm",
            "component_id": "CM-010",
            "registry_ref": "registry:ripe_hq:CM-010",
            "requires": ("address:SWITCHBOARD",),
            "abort_if": ("returned-registry-id-mismatch",),
            "postconditions": ("returned-registry-id-matches-authority",),
        },
    ),
}


def migrate(migration):
    migration.apply_robinhood_stage(MIGRATION_STAGE)
