MIGRATION_STAGE = {
    "migration_id": "0400",
    "semantic_id": "price-sources",
    "stage_kind": "deployment",
    "actions": (
        {
            "semantic_action_id": "deploy-price-desk",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-015",
            "artifact": "PriceDesk",
            "constructor": (
                "address:RIPE_HQ",
                "binding:temporary-local-governance",
                "address:NATIVE_ETH_SENTINEL",
                "input:Deployment.DP-05.timelocks.AddressRegistry.minDelay",
                "input:Deployment.DP-05.timelocks.AddressRegistry.maxDelay",
            ),
            "provides": ("address:PRICE_DESK",),
            "postconditions": ("price-desk-deployed", "price-desk-registry-empty"),
        },
        {
            "semantic_action_id": "deploy-chainlink-prices",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-016",
            "artifact": "ChainlinkPrices",
            "constructor": (
                "address:RIPE_HQ",
                "binding:temporary-local-governance",
                "input:Deployment.DP-05.timelocks.Chainlink.minTimeLock",
                "input:Deployment.DP-05.timelocks.Chainlink.maxTimeLock",
                "address:WETH",
                "address:NATIVE_ETH_SENTINEL",
                "address:BTC_SENTINEL",
                "input:Deployment.DP-23.external.chainlink.ethUsdFeed",
                "input:Deployment.DP-23.external.chainlink.btcUsdFeed",
                "input:Deployment.DP-17.staleWindows.chainlinkDefault",
            ),
            "provides": ("address:CHAINLINK_PRICES",),
            "postconditions": ("chainlink-prices-deployed",),
        },
        {
            "semantic_action_id": "configure-chainlink-usdg-feed",
            "kind": "configuration",
            "operation": "add-and-confirm-chainlink-feed",
            "component_id": "CM-016",
            "requires": ("address:USDG", "input:Deployment.DP-23.external.chainlink.usdgUsdFeed", "input:Deployment.DP-17.staleWindows.usdgCeiling"),
            "postconditions": ("usdg-is-chainlink-only",),
        },
        {
            "semantic_action_id": "resolve-curve-address-provider-and-factory",
            "kind": "configuration",
            "operation": "validate-external-identities",
            "component_id": "CM-017",
            "requires": (
                "curve:launch.chain_id",
                "curve:launch.component",
                "curve:launch.price_desk_registration_order",
                "curve:launch.priority_price_source_ids",
                "curve:curve.address_provider",
                "curve:curve.address_provider_binding_7",
                "curve:curve.address_provider_binding_11",
                "curve:curve.address_provider_binding_12",
                "curve:curve.address_provider_binding_13",
            ),
            "postconditions": (
                "curve-provider-and-factories-match-blueprint",
                "address-provider-ids-seven-eleven-twelve-thirteen-exact",
            ),
        },
        {
            "semantic_action_id": "deploy-curve-prices-unregistered",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-017",
            "artifact": "CurvePrices",
            "constructor": (
                "address:RIPE_HQ",
                "binding:temporary-local-governance",
                "curve:curve.address_provider",
                "address:GREEN_TOKEN",
                "address:SGREEN_TOKEN",
                "curve-binding:_minPriceChangeTimeLock",
                "curve-binding:_maxPriceChangeTimeLock",
            ),
            "requires": (
                "curve:curve.constructor_bindings",
                "curve:artifact.curve_prices_source_sha256",
                "curve:artifact.curve_prices_abi_sha256",
            ),
            "provides": ("address:CURVE_PRICES",),
            "postconditions": ("curve-prices-deployed", "curve-prices-not-registered"),
        },
        {
            "semantic_action_id": "create-or-bind-green-usdg-pool",
            "kind": "configuration",
            "operation": "create-or-bind-pool",
            "component_id": "CM-017",
            "requires": (
                "curve:pool.factory",
                "curve:pool.factory_method",
                "curve:pool.name",
                "curve:pool.symbol",
                "curve:pool.coin_order",
                "curve:pool.coin_decimals",
                "curve:pool.A",
                "curve:pool.fee",
                "curve:pool.offpeg_fee_multiplier",
                "curve:pool.ma_exp_time",
                "curve:pool.address",
                "curve:pool.factory_nonce_or_order",
                "curve:pool.production_liquidity_amount",
                "curve:pool.funding_source",
                "curve:pool.custodian",
                "curve:pool.approving_account",
                "curve:pool.minimum_minted_lp",
                "curve:pool.slippage_limit",
                "curve:pool.withdrawal_authority",
                "curve:pool.minimum_retained_liquidity",
            ),
            "provides": ("address:GREEN_USDG_CURVE_POOL",),
            "postconditions": ("green-usdg-pool-identity-recorded",),
        },
        {
            "semantic_action_id": "validate-green-usdg-pool",
            "kind": "assertion",
            "operation": "assert-pool-runtime",
            "component_id": "CM-017",
            "requires": (
                "address:GREEN_USDG_CURVE_POOL",
                "address:USDG",
                "address:GREEN_TOKEN",
                "curve:pool.ma_exp_time_alternative_test_vector",
                "curve:pool.production_observation",
            ),
            "postconditions": (
                "pool-factory-correct",
                "pool-runtime-correct",
                "coin-zero-usdg",
                "coin-one-green",
                "usdg-decimals-six",
                "green-decimals-eighteen",
                "pool-parameters-approved",
                "funding-controls-approved",
            ),
        },
        {
            "semantic_action_id": "register-chainlink-prices",
            "kind": "registration",
            "operation": "register-and-confirm",
            "component_id": "CM-016",
            "registry_ref": "registry:price_desk:CM-016",
            "requires": ("address:CHAINLINK_PRICES",),
            "abort_if": ("returned-registry-id-mismatch",),
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "validate-direct-green-pricing",
            "kind": "assertion",
            "operation": "assert-direct-price",
            "component_id": "CM-017",
            "requires": (
                "address:PRICE_DESK",
                "address:CHAINLINK_PRICES",
                "address:CURVE_PRICES",
                "address:GREEN_TOKEN",
                "address:USDG",
                "curve:feed.route",
                "curve:feed.curve_assets",
                "curve:feed.usdg_curve_feed",
                "curve:feed.usdg_authority",
                "curve:inactive.capabilities",
            ),
            "abort_if": (
                "green-price-validation-failed",
                "zero-price-input",
                "stale-chainlink-input",
                "invalid-pool-input",
                "abi-incompatible-pool-input",
                "reverting-pool-input",
                "unsafe-configuration",
                "pricing-recursion-detected",
                "curve-usdg-feed-present",
            ),
            "postconditions": (
                "green-route-composes-through-curve-and-chainlink-usdg",
                "usdg-prices-through-chainlink-only",
                "pricing-graph-nonrecursive",
                "next-price-desk-registration-id-is-two",
                "priority-one-and-three-fall-through-to-curve-two-for-green",
            ),
        },
        {
            "semantic_action_id": "register-curve-prices",
            "kind": "registration",
            "operation": "register-and-confirm",
            "component_id": "CM-017",
            "registry_ref": "registry:price_desk:CM-017",
            "requires": ("address:CURVE_PRICES", "action:validate-direct-green-pricing"),
            "abort_if": ("returned-registry-id-mismatch",),
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "register-price-desk-in-ripe-hq",
            "kind": "registration",
            "operation": "register-and-confirm",
            "component_id": "CM-015",
            "registry_ref": "registry:ripe_hq:CM-015",
            "requires": ("address:PRICE_DESK", "action:register-curve-prices"),
            "abort_if": ("returned-registry-id-mismatch",),
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "configure-curve-green-feed-at-id-two",
            "kind": "configuration",
            "operation": "add-and-confirm-curve-feed-after-id-two",
            "component_id": "CM-017",
            "requires": (
                "address:GREEN_TOKEN",
                "address:GREEN_USDG_CURVE_POOL",
                "action:register-price-desk-in-ripe-hq",
            ),
            "abort_if": (
                "green-feed-confirmation-failed",
                "curve-usdg-feed-present",
                "post-registration-green-price-failed",
            ),
            "postconditions": (
                "green-feed-configured",
                "curve-prices-registered-at-id-two",
                "green-resolves-through-curve-after-priority-miss",
                "usdg-remains-chainlink-only",
                "no-curve-usdg-feed",
            ),
        },
        {
            "semantic_action_id": "deploy-blue-chip-yield-prices",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-018",
            "artifact": "BlueChipYieldPrices",
            "constructor": (
                "address:RIPE_HQ",
                "binding:temporary-local-governance",
                "input:Deployment.DP-05.timelocks.Chainlink.minTimeLock",
                "input:Deployment.DP-05.timelocks.Chainlink.maxTimeLock",
                "binding:bluechip-morpho-factories",
                "binding:bluechip-euler-factories",
                "binding:bluechip-fluid-resolver",
                "binding:bluechip-compound-configurator",
                "binding:bluechip-moonwell-comptroller",
                "binding:bluechip-aave-provider",
                "input:Deployment.DP-23.external.blueChipYield.morphoV2Factory",
            ),
            "provides": ("address:BLUE_CHIP_YIELD_PRICES",),
            "postconditions": ("blue-chip-yield-prices-deployed", "morpho-v2-identity-exact"),
        },
        {
            "semantic_action_id": "register-blue-chip-yield-prices",
            "kind": "registration",
            "operation": "register-and-confirm",
            "component_id": "CM-018",
            "registry_ref": "registry:price_desk:CM-018",
            "requires": ("address:BLUE_CHIP_YIELD_PRICES",),
            "abort_if": ("returned-registry-id-mismatch",),
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "apply-price-desk-priority",
            "kind": "configuration",
            "operation": "set-priority-price-source-ids",
            "component_id": "CM-015",
            "requires": ("defaults:priority-price-source-ids",),
            "postconditions": ("price-priority-is-one-three",),
        },
        {
            "semantic_action_id": "assert-price-source-topology",
            "kind": "assertion",
            "operation": "assert-registry-sequence",
            "component_id": "CM-015",
            "requires": ("action:register-chainlink-prices", "action:register-curve-prices", "action:register-blue-chip-yield-prices"),
            "postconditions": (
                "price-desk-one-chainlink",
                "price-desk-two-curve",
                "price-desk-three-bluechip",
                "priority-one-three-before-curve-two",
                "green-composed-route-fails-closed",
                "usdg-chainlink-only",
                "pyth-and-stork-absent",
                "uniswap-unregistered",
            ),
        },
        {
            "semantic_action_id": "recover-disable-curve-id-two",
            "kind": "recovery",
            "operation": "pause-then-timelocked-disable-registry-address",
            "component_id": "CM-017",
            "registry_ref": "registry:price_desk:CM-017",
            "when": "post-registration-curve-failure",
            "postconditions": ("price-desk-id-two-zero", "green-has-no-unsafe-fallback", "bluechip-id-three-preserved"),
        },
        {
            "semantic_action_id": "recover-update-curve-id-two",
            "kind": "recovery",
            "operation": "timelocked-update-registry-address",
            "component_id": "CM-017",
            "registry_ref": "registry:price_desk:CM-017",
            "when": "approved-repair-after-direct-validation",
            "requires": ("binding:repaired-curve-prices", "binding:curve-repair-validation"),
            "postconditions": (
                "price-desk-id-two-restored-to-curve",
                "bluechip-id-three-preserved",
                "priority-one-three-preserved",
                "unrelated-placeholder-impossible",
            ),
        },
    ),
}


def migrate(migration):
    migration.apply_robinhood_stage(MIGRATION_STAGE)
