MIGRATION_STAGE = {
    "migration_id": "0500",
    "semantic_id": "vaults-and-assets",
    "stage_kind": "deployment",
    "actions": (
        {
            "semantic_action_id": "deploy-vault-book",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-021",
            "artifact": "VaultBook",
            "constructor": ("address:RIPE_HQ", "binding:temporary-local-governance", "input:Deployment.DP-05.timelocks.AddressRegistry.minDelay", "input:Deployment.DP-05.timelocks.AddressRegistry.maxDelay"),
            "provides": ("address:VAULT_BOOK",),
            "postconditions": ("vault-book-deployed",),
        },
        {
            "semantic_action_id": "deploy-stability-pool",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-022",
            "artifact": "StabilityPool",
            "constructor": ("address:RIPE_HQ",),
            "provides": ("address:STABILITY_POOL",),
            "postconditions": ("stability-pool-deployed",),
        },
        {
            "semantic_action_id": "register-stability-pool",
            "kind": "registration",
            "operation": "register-and-confirm",
            "component_id": "CM-022",
            "registry_ref": "registry:vault_book:CM-022",
            "requires": ("address:STABILITY_POOL",),
            "abort_if": ("returned-registry-id-mismatch",),
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "deploy-ripe-gov-vault",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-023",
            "artifact": "RipeGov",
            "constructor": ("address:RIPE_HQ",),
            "provides": ("address:RIPE_GOV_VAULT",),
            "postconditions": ("ripe-gov-vault-deployed",),
        },
        {
            "semantic_action_id": "register-ripe-gov-vault",
            "kind": "registration",
            "operation": "register-and-confirm",
            "component_id": "CM-023",
            "registry_ref": "registry:vault_book:CM-023",
            "requires": ("address:RIPE_GOV_VAULT",),
            "abort_if": ("returned-registry-id-mismatch",),
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "deploy-simple-erc20-vault",
            "kind": "deployment",
            "operation": "deploy",
            "component_id": "CM-024",
            "artifact": "SimpleErc20",
            "constructor": ("address:RIPE_HQ",),
            "provides": ("address:SIMPLE_ERC20_VAULT",),
            "postconditions": ("simple-erc20-vault-deployed",),
        },
        {
            "semantic_action_id": "register-simple-erc20-vault",
            "kind": "registration",
            "operation": "register-and-confirm",
            "component_id": "CM-024",
            "registry_ref": "registry:vault_book:CM-024",
            "requires": ("address:SIMPLE_ERC20_VAULT",),
            "abort_if": ("returned-registry-id-mismatch",),
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "register-vault-book-in-ripe-hq",
            "kind": "registration",
            "operation": "register-and-confirm",
            "component_id": "CM-021",
            "registry_ref": "registry:ripe_hq:CM-021",
            "requires": ("address:VAULT_BOOK",),
            "abort_if": ("returned-registry-id-mismatch",),
            "postconditions": ("returned-registry-id-matches-authority",),
        },
        {
            "semantic_action_id": "configure-profile-one-assets",
            "kind": "configuration",
            "operation": "apply-defaults-asset-configs",
            "component_id": "CM-012",
            "requires": ("defaults:asset-configs", "defaults:priority-price-source-ids"),
            "postconditions": ("only-profile-one-assets-configured", "profile-two-lp-assets-absent"),
        },
        {
            "semantic_action_id": "assert-rebase-vault-absent",
            "kind": "omission",
            "operation": "assert-component-and-registry-absent",
            "component_id": "CM-025",
            "registry_ref": "registry:vault_book:CM-025",
            "postconditions": ("rebase-vault-artifact-and-row-absent",),
        },
        {
            "semantic_action_id": "preserve-stock-extension-seam",
            "kind": "blocked",
            "operation": "assert-atomic-aapl-qualification-remains-blocked",
            "requires": (
                "stock:Deployment.DP-10.aapl.identity",
                "stock:Deployment.DP-10.aapl.feed",
                "stock:Deployment.DP-10.aapl.decimals",
                "stock:Deployment.DP-10.aapl.P8",
                "stock:Deployment.DP-10.aapl.perUserCap",
                "stock:Deployment.DP-10.aapl.globalCap",
                "stock:Deployment.DP-10.aapl.vault",
                "stock:Deployment.DP-10.aapl.risk",
                "stock:Deployment.DP-10.aapl.auction",
                "stock:Deployment.DP-10.aapl.route",
                "stock:Deployment.DP-11.stock.vaultArtifact",
                "stock:Deployment.DP-11.stock.vaultSlot",
                "stock:Deployment.DP-11.stock.m2Movement",
                "stock:Deployment.DP-11.stock.m3CreditContainment",
                "stock:Deployment.DP-11.stock.m4ComposedProof",
                "stock:Deployment.DP-11.stock.m5ActivationBinding",
            ),
            "postconditions": (
                "aapl-sixteen-input-census-bound",
                "aapl-four-repository-facts-resolved",
                "aapl-twelve-inputs-typed-blocked",
                "aapl-guarded-only",
                "aapl-stability-pool-excluded",
                "aapl-auction-only",
                "aapl-stock-rewards-disabled",
                "aapl-defaults-row-absent",
                "aapl-deployment-and-registration-absent",
            ),
        },
        {
            "semantic_action_id": "preserve-lp-extension-seam",
            "kind": "blocked",
            "operation": "declare-extension-seam",
            "requires": ("input:Deployment.DP-14.lp.oracleArtifacts",),
            "postconditions": (
                "green-usdg-pool-is-not-lp-asset-admission",
                "green-usdg-lp-asset-absent",
                "ripe-weth-lp-asset-absent",
                "psm-reserves-not-liquidity-funding",
                "uniswap-accounting-absent",
            ),
        },
    ),
}


def migrate(migration):
    migration.apply_robinhood_stage(MIGRATION_STAGE)
