MIGRATION_STAGE = {
    "migration_id": "0600",
    "semantic_id": "core-departments",
    "stage_kind": "deployment",
    "actions": (
        {"semantic_action_id": "deploy-auction-house", "kind": "deployment", "operation": "deploy", "component_id": "CM-026", "artifact": "AuctionHouse", "constructor": ("address:RIPE_HQ",), "provides": ("address:AUCTION_HOUSE",), "postconditions": ("auction-house-deployed", "mint-capability-withheld")},
        {"semantic_action_id": "register-auction-house", "kind": "registration", "operation": "register-and-confirm", "component_id": "CM-026", "registry_ref": "registry:ripe_hq:CM-026", "requires": ("address:AUCTION_HOUSE",), "abort_if": ("returned-registry-id-mismatch",), "postconditions": ("returned-registry-id-matches-authority",)},
        {"semantic_action_id": "deploy-auction-house-nft", "kind": "deployment", "operation": "deploy", "component_id": "CM-027", "artifact": "AuctionHouseNFT", "constructor": ("address:RIPE_HQ",), "provides": ("address:AUCTION_HOUSE_NFT",), "postconditions": ("auction-house-nft-deployed",)},
        {"semantic_action_id": "register-auction-house-nft", "kind": "registration", "operation": "register-and-confirm", "component_id": "CM-027", "registry_ref": "registry:ripe_hq:CM-027", "requires": ("address:AUCTION_HOUSE_NFT",), "abort_if": ("returned-registry-id-mismatch",), "postconditions": ("returned-registry-id-matches-authority",)},
        {"semantic_action_id": "deploy-boardroom", "kind": "deployment", "operation": "deploy", "component_id": "CM-028", "artifact": "Boardroom", "constructor": ("address:RIPE_HQ",), "provides": ("address:BOARDROOM",), "postconditions": ("boardroom-deployed",)},
        {"semantic_action_id": "register-boardroom", "kind": "registration", "operation": "register-and-confirm", "component_id": "CM-028", "registry_ref": "registry:ripe_hq:CM-028", "requires": ("address:BOARDROOM",), "abort_if": ("returned-registry-id-mismatch",), "postconditions": ("returned-registry-id-matches-authority",)},
        {"semantic_action_id": "deploy-bond-booster", "kind": "deployment", "operation": "deploy", "component_id": "CM-038", "artifact": "BondBooster", "constructor": ("address:RIPE_HQ", "input:Deployment.DP-22.bondBooster.maxBoostRatio", "input:Deployment.DP-22.bondBooster.maxUnits", "input:Deployment.DP-22.bondBooster.minLockDuration"), "provides": ("address:BOND_BOOSTER",), "postconditions": ("bond-booster-deployed",)},
        {"semantic_action_id": "deploy-bond-room", "kind": "deployment", "operation": "deploy", "component_id": "CM-029", "artifact": "BondRoom", "constructor": ("address:RIPE_HQ", "address:BOND_BOOSTER"), "provides": ("address:BOND_ROOM",), "postconditions": ("bond-room-deployed", "mint-capability-withheld")},
        {"semantic_action_id": "register-bond-room", "kind": "registration", "operation": "register-and-confirm", "component_id": "CM-029", "registry_ref": "registry:ripe_hq:CM-029", "requires": ("address:BOND_ROOM",), "abort_if": ("returned-registry-id-mismatch",), "postconditions": ("returned-registry-id-matches-authority",)},
        {"semantic_action_id": "deploy-credit-engine", "kind": "deployment", "operation": "deploy", "component_id": "CM-030", "artifact": "CreditEngine", "constructor": ("address:RIPE_HQ",), "provides": ("address:CREDIT_ENGINE",), "postconditions": ("credit-engine-deployed", "mint-capability-withheld")},
        {"semantic_action_id": "register-credit-engine", "kind": "registration", "operation": "register-and-confirm", "component_id": "CM-030", "registry_ref": "registry:ripe_hq:CM-030", "requires": ("address:CREDIT_ENGINE",), "abort_if": ("returned-registry-id-mismatch",), "postconditions": ("returned-registry-id-matches-authority",)},
        {"semantic_action_id": "deploy-endaoment", "kind": "deployment", "operation": "deploy", "component_id": "CM-031", "artifact": "Endaoment", "constructor": ("address:RIPE_HQ", "input:Deployment.DP-21.endaoment.wethIdentity", "address:NATIVE_ETH_SENTINEL"), "provides": ("address:ENDAOMENT",), "postconditions": ("endaoment-deployed", "stabilization-disabled")},
        {"semantic_action_id": "register-endaoment", "kind": "registration", "operation": "register-and-confirm", "component_id": "CM-031", "registry_ref": "registry:ripe_hq:CM-031", "requires": ("address:ENDAOMENT",), "abort_if": ("returned-registry-id-mismatch",), "postconditions": ("returned-registry-id-matches-authority",)},
        {"semantic_action_id": "deploy-human-resources", "kind": "deployment", "operation": "deploy", "component_id": "CM-032", "artifact": "HumanResources", "constructor": ("address:RIPE_HQ", "input:Deployment.DP-05.timelocks.HumanResources.minTimeLock", "input:Deployment.DP-05.timelocks.HumanResources.maxTimeLock"), "provides": ("address:HUMAN_RESOURCES",), "postconditions": ("human-resources-deployed", "mint-capability-withheld")},
        {"semantic_action_id": "register-human-resources", "kind": "registration", "operation": "register-and-confirm", "component_id": "CM-032", "registry_ref": "registry:ripe_hq:CM-032", "requires": ("address:HUMAN_RESOURCES",), "abort_if": ("returned-registry-id-mismatch",), "postconditions": ("returned-registry-id-matches-authority",)},
        {"semantic_action_id": "deploy-lootbox", "kind": "deployment", "operation": "deploy", "component_id": "CM-033", "artifact": "Lootbox", "constructor": ("address:RIPE_HQ", "binding:lootbox-min-send-interval", "binding:lootbox-send-interval", "binding:lootbox-deposit-reward", "binding:lootbox-yield-bonus"), "provides": ("address:LOOTBOX",), "postconditions": ("lootbox-deployed", "reward-actions-withheld-until-promotion-gates", "mint-capability-withheld")},
        {"semantic_action_id": "register-lootbox", "kind": "registration", "operation": "register-and-confirm", "component_id": "CM-033", "registry_ref": "registry:ripe_hq:CM-033", "requires": ("address:LOOTBOX",), "abort_if": ("returned-registry-id-mismatch",), "postconditions": ("returned-registry-id-matches-authority",)},
        {"semantic_action_id": "deploy-teller", "kind": "deployment", "operation": "deploy", "component_id": "CM-034", "artifact": "Teller", "constructor": ("address:RIPE_HQ", "input:Deployment.DP-20.teller.shouldPause"), "provides": ("address:TELLER",), "postconditions": ("teller-deployed-paused", "green-reference-snapshots-inactive")},
        {"semantic_action_id": "register-teller", "kind": "registration", "operation": "register-and-confirm", "component_id": "CM-034", "registry_ref": "registry:ripe_hq:CM-034", "requires": ("address:TELLER",), "abort_if": ("returned-registry-id-mismatch",), "postconditions": ("returned-registry-id-matches-authority",)},
        {"semantic_action_id": "deploy-deleverage", "kind": "deployment", "operation": "deploy", "component_id": "CM-044", "artifact": "Deleverage", "constructor": ("address:RIPE_HQ", "binding:deleverage-min-bps", "binding:deleverage-buffer", "blueprint:assertion:deleverage_launch_cooldown", "binding:deleverage-underscore-spread", "binding:deleverage-full-payoff-buffer", "binding:deleverage-overage-bps", "binding:deleverage-dust-threshold", "binding:deleverage-dust-bps"), "provides": ("address:DELEVERAGE",), "postconditions": ("deleverage-deployed", "cooldown-zero", "underscore-route-inactive")},
        {"semantic_action_id": "register-deleverage", "kind": "registration", "operation": "register-and-confirm", "component_id": "CM-044", "registry_ref": "registry:ripe_hq:CM-044", "requires": ("address:DELEVERAGE",), "abort_if": ("returned-registry-id-mismatch",), "postconditions": ("returned-registry-id-matches-authority",)},
        {"semantic_action_id": "deploy-credit-redeem", "kind": "deployment", "operation": "deploy", "component_id": "CM-043", "artifact": "CreditRedeem", "constructor": ("address:RIPE_HQ",), "provides": ("address:CREDIT_REDEEM",), "postconditions": ("credit-redeem-deployed", "stock-redemption-inactive")},
        {"semantic_action_id": "register-credit-redeem", "kind": "registration", "operation": "register-and-confirm", "component_id": "CM-043", "registry_ref": "registry:ripe_hq:CM-043", "requires": ("address:CREDIT_REDEEM",), "abort_if": ("returned-registry-id-mismatch",), "postconditions": ("returned-registry-id-matches-authority",)},
        {"semantic_action_id": "deploy-teller-utils", "kind": "deployment", "operation": "deploy", "component_id": "CM-045", "artifact": "TellerUtils", "constructor": ("address:RIPE_HQ",), "provides": ("address:TELLER_UTILS",), "postconditions": ("teller-utils-deployed",)},
        {"semantic_action_id": "register-teller-utils", "kind": "registration", "operation": "register-and-confirm", "component_id": "CM-045", "registry_ref": "registry:ripe_hq:CM-045", "requires": ("address:TELLER_UTILS",), "abort_if": ("returned-registry-id-mismatch",), "postconditions": ("returned-registry-id-matches-authority",)},
        {"semantic_action_id": "deploy-endaoment-funds", "kind": "deployment", "operation": "deploy", "component_id": "CM-047", "artifact": "EndaomentFunds", "constructor": ("address:RIPE_HQ",), "provides": ("address:ENDAOMENT_FUNDS",), "postconditions": ("endaoment-funds-deployed", "yield-destinations-inactive")},
        {"semantic_action_id": "register-endaoment-funds", "kind": "registration", "operation": "register-and-confirm", "component_id": "CM-047", "registry_ref": "registry:ripe_hq:CM-047", "requires": ("address:ENDAOMENT_FUNDS",), "abort_if": ("returned-registry-id-mismatch",), "postconditions": ("returned-registry-id-matches-authority",)},
        {"semantic_action_id": "deploy-endaoment-psm", "kind": "deployment", "operation": "deploy", "component_id": "CM-048", "artifact": "EndaomentPSM", "constructor": ("address:RIPE_HQ", "input:Deployment.DP-08.psm.numBlocksPer" "Interval", "input:Deployment.DP-08.psm.mintFee", "input:Deployment.DP-08.psm.maxMintPerInterval", "input:Deployment.DP-08.psm.redeemFee", "input:Deployment.DP-08.psm.maxRedeemPerInterval", "address:USDG", "input:Deployment.DP-07.psm.yield.amount", "input:Deployment.DP-07.psm.yield.asset"), "provides": ("address:ENDAOMENT_PSM",), "postconditions": ("endaoment-psm-deployed", "psm-not-activated")},
        {"semantic_action_id": "register-endaoment-psm", "kind": "registration", "operation": "register-and-confirm", "component_id": "CM-048", "registry_ref": "registry:ripe_hq:CM-048", "requires": ("address:ENDAOMENT_PSM",), "abort_if": ("returned-registry-id-mismatch",), "postconditions": ("returned-registry-id-matches-authority", "green-mint-capability-withheld")},
        {
            "semantic_action_id": "preserve-reward-promotion-seam",
            "kind": "blocked",
            "operation": "bind-approved-product-packet-and-operational-gates",
            "component_id": "CM-013",
            "requires": (
                "input:Deployment.DP-15.rewards.arePointsEnabled",
                "input:Deployment.DP-15.rewards.ripePer" "Block",
                "input:Deployment.DP-15.rewards.promotion",
                "defaults:rewards-config",
                "defaults:ripe-available-for-rewards",
                "binding:reward-initial-global-and-points-checkpoints",
                "binding:reward-governance-identity",
                "binding:reward-qualified-lite-signer-identity-if-used",
                "binding:reward-registered-ripe-checkpoint-caller",
                "binding:reward-monitoring-owners-thresholds-alerts-zero-budget-response",
                "binding:reward-minimum-runway-handling",
                "binding:reward-emergency-response-acceptance",
                "binding:reward-h06-operator-binding",
                "binding:reward-h08-post-deployment-assertions",
                "binding:reward-h09-qualification",
                "binding:reward-h10-rehearsal",
                "binding:reward-release-authorization",
            ),
            "postconditions": (
                "approved-reward-product-packet-bound-from-blueprint-and-defaults",
                "points-enabled-product-decision-preserved",
                "shared-reward-budget-product-decision-preserved",
                "stock-rewards-disabled",
                "reward-activation-remains-operationally-blocked",
                "reward-plan-hash-grants-no-lifecycle-authority",
            ),
        },
    ),
}


def migrate(migration):
    migration.apply_robinhood_stage(MIGRATION_STAGE)
